on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-pc-windows-msvc
      - run: cargo test --all-features
      - run: cargo build --release
      - uses: dlemstra/code-sign-action@v1
        with:
          certificate: ${{ secrets.CERTIFICATE }}
          password: ${{ secrets.CERTIFICATE_PASSWORD }}
          files: target/release/mocha.exe
      - uses: softprops/action-gh-release@v3
        with:
          files: target/release/mocha.exe
